### ISSUE TITLE
Make it as a library.

### ISSUE THREAD

**Issue by nareshchaudhary37** [harishbisht/paytm-django#3]
Can @harishbisht make paytm-django as an application, also add into pip for installation? 

It will be a very helpful to direct use for developers. :)  

Let me know if you need some help.

Thanks!

**Comment by harishbisht** [comment]
@nareshchaudhary37  [paytm](https://github.com/harishbisht/paytm) already in pip, please visit https://github.com/harishbisht/paytm , Thanks (:
